// src/features/electric/index.ts
export { default as electricReducer } from "./electricSlice";
export type { ElectricState } from "./electricSlice";
export {
  fetchElectricDevices,
  fetchElectricOverview,
  refreshElectricOverview,
  fetchElectricSeries,
  fetchMeterDashboard,
  fetchSiteMetersDashboard,
  type MeterDashboard,
  type RegisterElectricInput,
} from "./electricThunks";
export {
  getElectricDevices,
  syncElectricInventory,
  getElectricOverview,
  getElectricOverviewSummary,
  getElectricOverviewForSites,
  getUtilityOverviewSummary,
  getUtilityOverviewForSites,
  updateElectricOverview,
  getElectricSeries,
  registerElectricDevice,
  fetchEquipmentTelemetry,
  getMeterDashboard,
  getSiteMetersDashboard,
  type EquipmentFetchResp,
  type ElectricOverviewSummary,
  type UtilityOverviewSummary,
  type UtilitySubtype,
} from "./electricApi";
export {
  ALL_VENDORS,
  ELECTRIC_VENDOR_LABELS,
  ELECTRIC_VENDOR_ORDER,
  SOLAR_VENDORS,
  detectCustomerName,
  detectElectricVendor,
  isElectricVendorKey,
  isSolarVendor,
  type ElectricVendorFilter,
  type ElectricVendorKey,
} from "./electricVendor";
export {
  dailyEnergyFromCounters,
  isTariffConfigured,
  loadSiteSolarSavings,
  rateForDay,
  savingsForDays,
  solarDevicesFromItems,
  tariffFromSiteBilling,
  type DailyEnergy,
  type DeviceSolarSavings,
  type MonthlySolarSavings,
  type SavingsPeriod,
  type SiteSolarSavings,
  type SolarDeviceRef,
  type SolarTariff,
} from "./solarSavings";
