export type SiteRow = {
  id: string;
  name: string;
  code: string;
  groupId?: string | null;
  groupLabel?: string | null;
  utilityId?: string | null;
  utilityLabel?: string | null;
  provinceLabel: string;
  lat: number | null;
  lng: number | null;
  zipcode?: string | null;
  addressProvince?: string | null;
  addressDistrict?: string | null;
  addressSubDistrict?: string | null;
  addressLine?: string | null;
  brandingLogoUrl?: string | null;
  devicesTotal: number;
  usersCount: number;
  updatedAt?: string | null;
  allowElectricBilling?: boolean;
  allowWaterBilling?: boolean;
  billingOnPeakRate?: number | null;
  billingOffPeakRate?: number | null;
  billingDiscountRate?: number | null;
  billingFtRate?: number | null;
  billingCo2Factor?: number | null;
  billingTreeFactor?: number | null;
  inverterApiType?: string;
  solaredgeSiteId?: string | null;
  solaredgeApiKey?: string | null;
  solisKeyId?: string | null;
  solisKeySecret?: string | null;
  solisStationId?: string | null;
};

export const SITE_ROWS: SiteRow[] = [];
